apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      imagePullSecrets: 
      - name: pull-acr
      containers:
      - name: test-cont
        image: acrpubcon.azurecr.io/node-test:5cde6d38c5de00b37f1aa12b8335860bc79b23c7
        ports:
        - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6080
  selector:
    app: testdeploy

