apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      imagePullSecrets: 
      - name: pull-acr
      containers:
      - name: test-cont
        image: acrpubcon.azurecr.io/node-test:04d2bd3e27c7ea34e5948a64cb2c5246e9d4d639
        ports:
        - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
