apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: testdeploy
namespace: default
resources:
- ../../base
images:
- name: acrpubcon.azurecr.io/node-test
  newTag: ffd17d057e1f7bb837e987ccf5dccb2e53310be7
