apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: testdeploy
namespace: default
resources:
- ../../base
images:
- name: acrpubcon.azurecr.io/node-test
  newTag: abc
